### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by MACEL94**

### CODE REVIEW

**Comment by MACEL94** [comment]
@tshaiman

**Comment by MACEL94** [comment]
@tshaiman

**Comment by IngridAtMicrosoft** [comment]
@MACEL94 Thanks for catching that! Before I can merge your changes, there are branch conflicts that need to be resolved first.  Do you have the ability to do this?

**Review by tshaiman — APPROVED** [review]

**Comment by tshaiman** [comment]
@MACEL94 just a minor branch merge and we are good to go , thanks for catching this

**Comment by IngridAtMicrosoft** [comment]
There is still a merge conflict.

**Comment by tshaiman** [comment]
@IngridAtMicrosoft yes I know , i’ve asked @MACEL94 to patch it as i’m OOO

**Comment by MACEL94** [comment]
@IngridAtMicrosoft please check again when you can :)

sorry but i'm from Italy and i couldn't fix this right away last night

**Pull request merged**
